version: '3.7'
services:
  db:
    image: postgres:10.11-alpine
    restart: always
    volumes:
      - /postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
