version: '3.3'
services:
  db:
    image: postgres:10.11-alpine
    restart: always
    volumes:
      - /postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - ./env/variables.env
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
